layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
    - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  #instagram: chaudhurijeet
  # keybase: your_username
  linkedin: jeetch
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
   image_url: https://pluralsight.imgix.net/paths/python-7be70baaac.png

  - name: Machine Learning
  image_url: https://www.netclipart.com/pp/m/358-3580619_networking-sice-sa-artificial-neural-network-png.png
